@startuml
skinparam DefaultFontName "Lucida Sans Typewriter"

skinparam UseCase{
    BorderColor DarkSlateBlue
    BackgroundColor whitesmoke
}
skinparam Note{
    BorderColor DarkSlateBlue
    BackgroundColor LightYellow
}

skinparam Actor{
    BorderColor DarkSlateBlue
    BackgroundColor whitesmoke
}

skinparam ArrowColor DarkSlateBlue

'Generell zum Lesen von Use-Case-Diagrammen einfacher:
left to right direction

actor :{abstract}\n<i>Befugte</i>: as befugte
actor :Prokuristin: as prokuristin
actor :Geschäftsführerin: as gf

rectangle Vertragswesen {
  usecase (Vertrag \n unterschreiben) as unterschreiben

  befugte -- unterschreiben
  befugte <|- prokuristin
  gf -|> befugte 
}
@enduml
